CREATE TABLE IF NOT EXISTS business_stats (
  id SERIAL PRIMARY KEY,
  rating NUMERIC NOT NULL,
  user_ratings_total INTEGER NOT NULL,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
